@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Order {
Class Order
Class Description
Class Date
Class Client
Class OrderAddress
Class UniqueOrderList
}

Package Client {
Class Client
Class ClientAddress
Class Email
Class Name
Class Phone
Class UniquePersonList
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" AddressBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList o--> "*" Client
Client *--> Name
Client *--> Phone
Client *--> Email
Client *--> ClientAddress

AddressBook *--> "1" UniqueOrderList
UniqueOrderList o--> "*" Order
Order *--> Description
Order *--> OrderAddress
Order *--> Date
Order *--> Client

Name -[hidden]right-> Phone
Phone -[hidden]right-> ClientAddress
ClientAddress -[hidden]right-> Email

Description -[hidden]right-> OrderAddress
OrderAddress -[hidden]right-> Date
Date -[hidden]right-> Client
Order -[hidden]left-> Client

ModelManager -->"1" Client : filtered client list
ModelManager -->"1" Order : filtered order list
@enduml
